name: "Humble 24.03 Raspberry Pi 4 Build"

on:
  schedule:
    - cron: '0 2 * * 0'  # every Sunday at 02:00 UTC

  workflow_dispatch:

jobs:
  build-humble:
    uses: ./.github/workflows/vxworks-ros2-build.yaml
    with:
      ros_distro: humble
      vxworks: "24.03"
      sdk: raspberrypi4b
      test: false
      debug: false
