name: "Jazzy 25.09 Raspberry Pi 4 Build"

on:
  schedule:
    - cron: '0 5 * * 0'  # every Sunday at 05:00 UTC

  workflow_dispatch:

jobs:
  build-jazzy:
    uses: ./.github/workflows/vxworks-ros2-build.yaml
    with:
      ros_distro: jazzy
      vxworks: "25.09"
      sdk: raspberrypi4b
      test: false
      debug: false
