name: "Jazzy 25.09 QEMU Build"

on:
  schedule:
    - cron: '0 4 * * 0'  # every Sunday at 04:00 UTC

  workflow_dispatch:

jobs:
  build-jazzy:
    uses: ./.github/workflows/vxworks-ros2-build.yaml
    with:
      ros_distro: jazzy
      vxworks: "25.09"
      sdk: qemu
      test: false
      debug: false
